builds:
  - binary: mogo
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prelease: auto

universal_binaries:
  - replace: true

brews:
  - name: mogo
    homepage: https://github.com/eldanielhumberto/mogo
    tap:
      owner: eldanielhumberto
      name: homebrew-mogo
    commit_author:
      name: eldanielhumberto
      email: eldanielhumberto@gmail.com

checksum:
  name_template: "checksums.txt"
